### PR TITLE
Spelling, coding style and indention stuff.

### PR DESCRIPTION
**Pull request by ypid**
Seems like I have to push early to avoid merge conflicts because the DebOps project is under rapid development :smile: :+1:

### CODE REVIEW

**Comment by drybjed** [comment]
@ypid Most roles don't even have version 1.0 yet. ;-) BTW, are you a PostgreSQL user?

**Comment by ypid** [comment]
I have a few PostgresSQL server instances running with Icinga and ownCloud. I use both MariaDB and PostgresSQL. So you could say that I am a PostgreSQL server …

**Comment by drybjed** [comment]
@ypid I'm setting up new [PostgreSQL Server](https://github.com/debops/ansible-postgresql_server/compare/master...drybjed:postgresql_server_rewrite) and [PostgreSQL Client](https://github.com/debops/ansible-postgresql/compare/master...drybjed:postgresql_rewrite) roles, you might want to check them out. The base changes are done, now I'm writing the docs.

**Comment by ypid** [comment]
Thanks for the hint. Unfortunately none of my PostgrsSQL servers is managed by DebOps yet. Some are running in Docker. I will see. I noticed your rewrite of the PostgreSQL role.

**Pull request merged**
