### PR TITLE
Rework 5

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by ypid** [comment]
@drybjed Can you merge as https://github.com/debops/ansible-owncloud/pull/83 now depends on this? Not really a hard dependency, but still.

**Comment by drybjed** [comment]
I'll be able to on Monday.

03.06.2017 23:27 "Robin Schneider" <notifications@github.com> napisał(a):

**Comment by drybjed** [comment]
@ypid Done. Do you need a new role release for `debops.owncloud` test on Travis, or can it wait a bit?

**Comment by ypid** [comment]
Can wait. Thanks :+1:

**Pull request merged**
