### PR TITLE
Template for Yii2 Framework

### PR DESCRIPTION
**Pull request by thiagotalma**
Following the official instructions here: https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#preparing-application

### CODE REVIEW

**Comment by drybjed** [comment]
I haven't checked that throughly yet, but it seems the biggest different between this template and `php5` template seems to be:
```
{% block nginx_tpl_block_location_root %}
                try_files $uri $uri/ /index.php?$args;
{% endblock %}
```
In the `php5` template this is set as:
```
{% block nginx_tpl_block_location_root %}
                try_files $uri $uri/ /index.php =404;
{% endblock %}
```


Not sure about the rest of the template. Since most of the PHP5 applications that I've seen use similar `try_files` line in `nginx`, I would go and change the default in `php5` template instead; I don't think it would break anything.

Is there anything else important in `yii2` template that could be added to the `php5` template instead? As for the separate deny section, maybe specifying `item.deny_regex` could add something like this in default template. I'll look into it.

**Comment by carlalexander** [comment]
I'm not sure it should be the responsibility of `debops.nginx` to have templates for every possible framework. It should be the responsibility of the Yii2 role to pass the right configuration options to `debops.nginx`.

**Comment by thiagotalma** [comment]
@carlalexander , create templates to frameworks was the brainchild of @drybjed

But I agree with you. However, the templates should be more smart. Today they are very limited.

**Comment by drybjed** [comment]
Yes, I suggested that a separate template for Yii2 framework could be done, but I thought that it would have more changes than this. :-) So I'm down to changing the default `try_files` line in `php5` template since that seems to be most commonly changed these days. Anything else you would like me to look into? Other than that, this template looks very similar to the current 'php5' template, and configuring `debops.nginx` via dependent variables would be the way to go.

**Comment by thiagotalma** [comment]
@drybjed , I also think it could be solved with settings.

I suggest you turn the location_root on a default variable from role and also create a template variable, so that you can override the default.

In my opinion, the most configurable, the better.
The default should always surrender to personalization.

**Comment by carlalexander** [comment]
Agreed, I submitted a bunch of PRs myself when I was working on my WordPress role.

**Pull request closed without merging**
