### PR TITLE
Added options to rename access and error logs

### PR DESCRIPTION
**Pull request by carlalexander**
This lets you change the log names when you use the same server name in multiple server configurations.

### CODE REVIEW

**Comment by drybjed** [comment]
There's also `item.filename` available to specify static nginx server config filename. Could you do something like this instead?
```
access_log /var/log/nginx/{{ item.access_log | d(item.filename | d(item.name[0]) + '_access') }}.log;
error_log /var/log/nginx/{{ item.error_log | d(item.filename | d(item.name[0]) + '_error') }}.log;
```

**Comment by carlalexander** [comment]
Yep! Will update the PR today.

**Comment by carlalexander** [comment]
Alright, I lied :stuck_out_tongue:! Updated the PR already.

**Comment by drybjed** [comment]
@carlalexander Looking good, thank you.

**Pull request merged**
